### ISSUE TITLE
Improve Phoebus UI for scan monitoring

### ISSUE THREAD

**Issue by ulrikpedersen** [ulrikpedersen/tomoscan#10]
Improve the supplied phoebus UI screens for users monitoring the scan:

* Maintain image display and combined plot with laser pulses, detector status and motor position
  - Consider adding motor move status bit to the plot
  - Remove other plots or move to a more advanced "specialist" screen
* Add a motor overview display, perhaps from an embedded display from the motor record module.
* Add a detector overview display - or a button to launch detector and plugin displays

**Comment by 8ryn** [comment]
Improvements merged in #17
