### ISSUE TITLE
Implement support for scan pausing

### ISSUE THREAD

**Issue by ulrikpedersen** [ulrikpedersen/tomoscan#13]
BlueSky does have a mechanism to support pausing (and resuming) scans. This is another important feature for end-users that we should enable.

Implement the pause functionality first in the BlueSky driven step-scan (the easier one, presumably). This would be a nice-to-have for the first Demo.

Consider how this could be implemented also for the "hardware-triggered" scan scenario.

**Comment by 8ryn** [comment]
This is implemented in the current version of the plans due to the use of the checkpoint() Bluesky plan stub. This works as expected for the Bluesky driven step-scan. 
In the case of the "hardware-triggered" scan the motor will pause but the detector will continue capturing frames.

**Comment by ulrikpedersen** [comment]
Closing for now as there is no specific work here ATM.

Do keep scan pausing in mind when implementing future hardware triggered scans and also when performing demos.
