### ISSUE TITLE
Try out apstools ohpyd areadetector support

### ISSUE THREAD

**Issue by ulrikpedersen** [ulrikpedersen/tomoscan#20]
Have a go at adopting apstools and try out its implementation of [areaDetector ophyd device classes](https://github.com/BCDA-APS/apstools/blob/main/apstools/devices/area_detector_support.py) as described in the [guides](https://bcda-aps.github.io/apstools/1.6.17/examples/index.html).

**Comment by 8ryn** [comment]
Work on this can be seen in my branch here: https://github.com/8ryn/tomoscan/tree/apstools_test
This work lead to the discovery that the hdf plugin needed to have its "kind" set to allow the image to be read from the databroker this resolved issue #11 .

**Comment by ulrikpedersen** [comment]
Closing this as looking into apstools package actually led to the discovery of the primary issue that we were having (on #11)

While there are some useful snippets in apstools to learn from, we do not want to add this dependency wholesale.
