### ISSUE TITLE
Installation and tutorial documentation

### ISSUE THREAD

**Issue by ulrikpedersen** [ulrikpedersen/tomoscan#5]
Add to the existing documentation to include:

* Download and install instructions
  - Assuming (and documenting that assumption) an Ubuntu 22.04 OS
  - Git clone...
  - Docker, vscode (and extensions), etc
* How to spin up the environment and check that it is running
  - `docker compose up -d`
* How to configure and run the scan(s)
  - Run up Phoebus to monitor the progress

**Comment by 8ryn** [comment]
Basic instructions have been added to the README at https://github.com/8ryn/tomoscan/tree/documentation-updates

**Comment by ulrikpedersen** [comment]
Please add this instead to the documentation sources in `docs/` so that it gets built into published docs here: https://ulrikpedersen.github.io/tomoscan/main/index.html

**Comment by ulrikpedersen** [comment]
Docs were updated to reflect installation and use at demo 1 time.
